title: Button switches, Scratch 3, and Raspberry Pi 4
hero_image: images/banner.png
description: button-switch-scratch-pi description
version: 4
listed: true
copyedit: true
last_tested: "2020-02-25"
steps:
  - title: Introduction
  - title: Button basics
  - title: A random button
  - title: "Challenge: a more random button"
    challenge: true
  - title: Controlling an LED
  - title: Controlling an LED sequence
  - title: "Challenge: which LED?"
    challenge: true   
  - title: What next?
