title: Button switches, Scratch 3 and Raspberry Pi 4
hero_image: images/banner.png
description: button-switch-scratch-pi description
version: 4
listed: false
copyedit: false
last_tested: "2019-11-05"
steps:
  - title: Introduction
  - title: Button basics
  - title: A random button
  - title: Controlling an LED
  - title: "Challenge: Which LED?"
    challenge: true
