title: button-switch-scratch-pi
hero_image: images/banner.png
description: button-switch-scratch-pi description
version: 4
listed: false
copyedit: false
last_tested: "2019-11-05"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
